### ISSUE TITLE
Two way connections

### ISSUE THREAD

**Issue by spllr** [shogo4405/SRTHaishinKit.swift#2]
In `SRTConnection` two srt sockets are established when calling `SRTConnection.connect(:)`.

From `SRTConnection.swift:31`:

```swift
outgoingSocket = SRTOutgoingSocket()
outgoingSocket?.delegate = self
((try? outgoingSocket?.connect(addr, options: options)) as ()??)

incomingSocket = SRTIncomingSocket()
incomingSocket?.delegate = self
((try? incomingSocket?.connect(addr, options: options)) as ()??)
```

My question is: is this specific for a server you (@shogo4405) are working with, or is this part of the srt protocol, as I have not been able to find any mention of this in the srt documentation or srt sample code.

**Comment by themaxsmith** [comment]
I agree that it should be only one socket. one SRT socket can send data in ether way

**Comment by themaxsmith** [comment]
new PR request to make this library work with standard 'srt-live-transmit'
