### ISSUE TITLE
VTDecompressionSessionDecodeFrame fails with OSStatus=-12909

### ISSUE THREAD

**Issue by shogo4405** [shogo4405/SRTHaishinKit.swift#57]
### Discussed in https://github.com/shogo4405/SRTHaishinKit.swift/discussions/56

<div type='discussions-op-text'>

<sup>Originally posted by **martinzsapka** May 10, 2023</sup>
Hello!

I'm trying to receive an h264 srt stream, but the decoder fails with error OSStatus=-12909. Specifically, the VTDecompressionSessionDecodeFrame call. Of course because of that, I don't get any imagebuffer.

Do you have any guesses as to what I may have misplaced? Maybe some configuration is missing?

Thanks!</div>

**Comment by kovmarton** [comment]
> ### Discussed in #56
> 
> Originally posted by **martinzsapka** May 10, 2023 Hello!
> 
> I'm trying to receive an h264 srt stream, but the decoder fails with error OSStatus=-12909. Specifically, the VTDecompressionSessionDecodeFrame call. Of course because of that, I don't get any imagebuffer.
> 
> Do you have any guesses as to what I may have misplaced? Maybe some configuration is missing?
> 
> Thanks!

Hi! I got the same error. When is it expected to be fixed? Thanks in advance!
