### ISSUE TITLE
Can't add the package

### ISSUE THREAD

**Issue by LambdaXe** [shogo4405/SRTHaishinKit.swift#61]
**Describe the bug**
When I try to put the package in the package dependencies, and try to compile it says
```
"Failed to resolve dependencies Dependencies could not be resolved because root depends on 'srthaishinkit.swift' 0.1.2..<1.0.0.
'srthaishinkit.swift' >= 0.1.2 cannot be used because no versions of 'srthaishinkit.swift' match the requirement 0.1.3..<1.0.0 and package 'srthaishinkit.swift' is required using a stable-version but ' srthaishinkit.swift' depends on an unstable-version package 'haishinkit.swift'."
```

**To Reproduce**
1. Click on "File"
2. "Add Packages..."
3. Enter the package url on the top right "https://github.com/shogo4405/SRTHaishinKit.swift"
4. Default settings for Dependency Rule "Up to Next Major Version: 0.1.2<1.0.0")
5. Click on "Add Package"

**Expected behavior**
When I add the package, it doesn't give dependency issues

**Comment by shogo4405** [comment]
I believe this issue has been fixed with this commit https://github.com/shogo4405/SRTHaishinKit.swift/commit/7a43413e20422f6c94e68680c66e37122a45f952. If you want to use it immediately, I think it should work if you specify the main branch.
