### ISSUE TITLE
Not able to run project in xcode 11.2

### ISSUE THREAD

**Issue by prashantwynk** [shogo4405/SRTHaishinKit.swift#7]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by themaxsmith** [comment]
Unable to re-create. What exact error are you getting?

**Comment by themaxsmith** [comment]
Not able to re-create. make sure you have cmake installed prior to carthage update --platform iOS

**Comment by themaxsmith** [comment]
PR created to make this clear on Readme
